# Logo
logo: css/images/logo.png # Empty this to unset logo and show site title in the same place

# Header
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
  #RSS: /atom.xml
  #Sitemap: /sitemap.xml

# Content
excerpt_link: Read More
fancybox: true

# Profile
profile: true # Whether to show profile bar
gravatar: false # Whether to use gravatar with the email. If you do, put your email address in your site's `_config.yml`.

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
- links
thumbnail: true

# Contacts
contacts:
  twitter: 'https://twitter.com/Kobe_Chen_1992'
  facebook: 'https://www.facebook.com/kobe.chen.5667'
  weibo: 'http://weibo.com/dmuchenyang'
  rss: '/atom.xml'

# Links
links:
  大连海事大学海之魂论坛: http://www.dlmubbs.com
  Hexo: http://hexo.io
  
# Rss & Sitemap
rss: /atom.xml
sitemap: /sitemap.xml

## Analytics
cnzz_tongji: true

# CDN
cdn: # You can choose "useso" instead of "google apis"(default).
# cdn: useso
# OR
# cdn:

# Miscellaneous
google_site_verification:
google_analytics:
favicon: favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
